# Generated by Django 6.0.5 on 2026-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourismPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Temples', 'Temples'), ('Waterfalls', 'Waterfalls'), ('Historical Places', 'Historical Places'), ('Parks', 'Parks'), ('Adventure Spots', 'Adventure Spots'), ('View Points', 'View Points')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('distance', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
