# Generated by Django 6.0.5 on 2026-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='image',
            field=models.ImageField(upload_to='tourism/'),
        ),
    ]
