# Generated by Django 6.0.5 on 2026-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_hotellocation_tourismplace_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='category',
            field=models.CharField(choices=[('Temples', 'Temples'), ('Waterfalls', 'Waterfalls'), ('Historical Places', 'Historical Places'), ('Parks', 'Parks')], max_length=50),
        ),
    ]
