# Generated by Django 6.0.5 on 2026-06-26 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_tourismplace_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
