# Generated by Django 6.0.5 on 2026-06-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
