# Generated by Django 6.0.1 on 2026-06-29 06:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventcategory_image_eventcategory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
