# Generated by Django 6.0.5 on 2026-06-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('DELUXE', 'Deluxe'), ('PREMIUM', 'Premium'), ('SUITE', 'Suite'), ('EXECUTIVE', 'Executive')], max_length=20)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('feature1', models.CharField(max_length=100)),
                ('feature2', models.CharField(max_length=100)),
                ('feature3', models.CharField(max_length=100)),
                ('feature4', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
