# Generated by Django 6.0.5 on 2026-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
