# Generated by Django 6.0.5 on 2026-06-26 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0002_room_available_rooms_room_total_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
