# Generated by Django 6.0.5 on 2026-07-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0003_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='feature4',
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('available_rooms__lte', models.F('total_rooms'))), name='available_lte_total'),
        ),
    ]
