# Generated by Django 6.0.5 on 2026-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
