# Generated by Django 6.0.1 on 2026-06-01 12:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Starters', 'Starters'), ('Drinks', 'Drinks'), ('Ice Creams', 'Ice Creams'), ('Restaurant Specials', 'Restaurant Specials')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
